@ECHO OFF
	
ECHO SETTING EXECUTION POLICY

ECHO EXECUTION POLICY SET TO UNRESTRICTED

ECHO SETTING VARIABLES...

SET CUR_DIR="%cd%"
SET PS_FILE=AutomatedSystemRestore.ps1
SET STARTUP_DIR="C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"

SET WRAPPER_FILE=%STARTUP_DIR%\runWrapper.bat
SET WRAPPER_CMD=PowerShell.exe -ExecutionPolicy Bypass -File %CUR_DIR%\%PS_FILE%

ECHO WROTE VARIABLES.
ECHO WRITTING FILE...

TYPE nul>%WRAPPER_FILE%
ECHO @ECHO OFF>>%WRAPPER_FILE%
ECHO %WRAPPER_CMD%>>%WRAPPER_FILE%

ECHO WROTE FILE %WRAPPER_FILE%...
ECHO CONTENTS:
TYPE %WRAPPER_FILE%

ECHO DONE.
PAUSE

:ExecutionPolicySetup
	